services:
  backend1:
    build: ./backend
    restart: always
    env_file: .env
    volumes:
      - ./dataset:/app/dataset
      - ./backend/logs:/logs
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - remap

  backend2:
    build: ./backend
    restart: always
    env_file: .env
    volumes:
      - ./dataset:/app/dataset
      - ./backend/logs:/logs
    ports:
      - "127.0.0.1:8001:8000"
    networks:
      - remap
    cpuset: "1"

networks:
  remap:
    driver: bridge
