services:
  remap-backend:
    build:
      context: ./backend
    env_file:
      - .env
    volumes:
      # ✅ FIXED: host:container
      - ./dataset:/app/dataset  # Mount host ./dataset to /app/dataset
      - ./backend/logs:/logs  # ← ADD THIS LINE

    ports:
      - "8000:8000"
    container_name: backend
    networks:
      - remap

  remap-frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    container_name: frontend
    environment:
      - API_URL=http://backend:8000
    networks:
      - remap

networks:
  remap:
    driver: bridge
